/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import javax.swing.ListModel;
import rede.SocketCliente;

/**
 *
 * @author vitor
 */
public class TelaCliente extends javax.swing.JFrame {
    TrataSocket socket;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaCliente() {
        initComponents();
        
        /*
        PainelMensagem painelMsg = new PainelMensagem(jScrollPane2, "Teste");
        
        for (int i = 0; i < 3; i++) {
            new PainelMensagem(jScrollPane2, "Teste");
        }
        
        SocketCliente sc = new SocketCliente();
        sc.conectarAoServidor(servidorIP);
        */
        
        //adicionarMensagemAoChat("Teste"); // Funciona!
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnConexao = new javax.swing.JPanel();
        btConectar = new javax.swing.JButton();
        tfConexaoEndereco = new javax.swing.JTextField();
        lbConexaoEndereco = new javax.swing.JLabel();
        tfConexaoNome = new javax.swing.JTextField();
        lbConexaoNome = new javax.swing.JLabel();
        pnOnline = new javax.swing.JPanel();
        lbOnlineTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsOnlineLista = new javax.swing.JList<>();
        tfInputMensagem = new javax.swing.JTextField();
        spChat = new javax.swing.JScrollPane();
        lsChat = new javax.swing.JList<>();
        lbVersao = new javax.swing.JLabel();
        btInputEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        pnConexao.setBackground(new java.awt.Color(255, 255, 255));
        pnConexao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btConectar.setText("Conectar");
        btConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConectarActionPerformed(evt);
            }
        });

        lbConexaoEndereco.setText("Endereço IP:");

        lbConexaoNome.setText("Nome de usuário:");

        javax.swing.GroupLayout pnConexaoLayout = new javax.swing.GroupLayout(pnConexao);
        pnConexao.setLayout(pnConexaoLayout);
        pnConexaoLayout.setHorizontalGroup(
            pnConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnConexaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbConexaoEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfConexaoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btConectar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbConexaoNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfConexaoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnConexaoLayout.setVerticalGroup(
            pnConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnConexaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConectar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfConexaoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbConexaoEndereco)
                    .addComponent(tfConexaoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbConexaoNome))
                .addContainerGap())
        );

        pnOnline.setBackground(new java.awt.Color(153, 153, 153));
        pnOnline.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lbOnlineTitulo.setBackground(new java.awt.Color(204, 204, 204));
        lbOnlineTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbOnlineTitulo.setText("ONLINE:");
        lbOnlineTitulo.setOpaque(true);

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lsOnlineLista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(lsOnlineLista);

        javax.swing.GroupLayout pnOnlineLayout = new javax.swing.GroupLayout(pnOnline);
        pnOnline.setLayout(pnOnlineLayout);
        pnOnlineLayout.setHorizontalGroup(
            pnOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOnlineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lbOnlineTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnOnlineLayout.setVerticalGroup(
            pnOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOnlineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbOnlineTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );

        tfInputMensagem.setToolTipText("");

        spChat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lsChat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spChat.setViewportView(lsChat);

        lbVersao.setText("v0.0.1");

        btInputEnviar.setText("Enviar");
        btInputEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInputEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnConexao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spChat, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfInputMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(btInputEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(pnOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbVersao)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnConexao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(spChat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfInputMensagem)
                            .addComponent(btInputEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                    .addComponent(pnOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(lbVersao))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConectarActionPerformed
        criarConexao(tfConexaoEndereco.getText(), tfConexaoNome.getText());
    }//GEN-LAST:event_btConectarActionPerformed

    private void btInputEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInputEnviarActionPerformed
        socket.EscreverCanal(tfInputMensagem.getText());
    }//GEN-LAST:event_btInputEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConectar;
    private javax.swing.JButton btInputEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbConexaoEndereco;
    private javax.swing.JLabel lbConexaoNome;
    private javax.swing.JLabel lbOnlineTitulo;
    private javax.swing.JLabel lbVersao;
    private javax.swing.JList<String> lsChat;
    private javax.swing.JList<String> lsOnlineLista;
    private javax.swing.JPanel pnConexao;
    private javax.swing.JPanel pnOnline;
    private javax.swing.JScrollPane spChat;
    private javax.swing.JTextField tfConexaoEndereco;
    private javax.swing.JTextField tfConexaoNome;
    private javax.swing.JTextField tfInputMensagem;
    // End of variables declaration//GEN-END:variables

    // Começo métodos customizados:
    // Parte visual
    public void adicionarMensagemAoChat(String mensagem) {
        // Gerar versão atualizada da lista
        ListModel lm = lsChat.getModel();
        String[] novaLista = new String[lm.getSize() + 1];        
        
        for (int i = 0; i < lm.getSize(); i++) {
            novaLista[i] = lm.getElementAt(i).toString();
        }
        
        // Adicionar nova mensagem
        novaLista[novaLista.length - 1] = mensagem;  
        
        lsChat.setListData(novaLista);
    }
    
    // Conexão de rede
    private void criarConexao(String servidorIP, String nomeUsuario) {
        TrataSocket ts = new TrataSocket(this, servidorIP, nomeUsuario);
        ts.start();
    }
}

class TrataSocket extends Thread {
    String servidorIP;
    String nomeUsuario;
    SocketCliente socket;
    TelaCliente tela;
    BufferedReader in;
    PrintWriter out;
    
    public TrataSocket(TelaCliente tela, String ip) {
        this(tela, ip, "Usuario");
    }
    
    public TrataSocket(TelaCliente tela, String ip, String nome) {
        this.servidorIP = ip;
        this.tela = tela;
        this.nomeUsuario = nome;
    }
    
    public void run() {
        socket = new SocketCliente();
        tela.socket = this;
        
        boolean conectou = false;
        
        for (int i = 0; i < 5; i++) {
            try {
                socket.conectarAoServidor(servidorIP, nomeUsuario);
                conectou = true;
            } catch (Exception e) {
                System.out.println("ERRO (iniciarConexao): " + e.getMessage());
            }
            
            if (conectou) {
                in = socket.RetornarCanalDeEntrada();
                out = socket.RetornarCanalDeSaida();
                
                // Primeiro emitir o nome de usuario (TRATADO PELO SocketCliente!!!)
                //EscreverCanal(nomeUsuario);
                //System.out.println("*** ATENÇÃO: (tire esse print) ARRUMAR PARTE DE CONFIGURACAO DE USUARIO ***");
                
                // Bloquear na escuta do canal
                OuvirCanal(in);
            } else {
                tela.adicionarMensagemAoChat("[SISTEMA] Conexão falhou.");
                
                // Breve sleep para esperar um pouco antes de tentar conectar novamente                
                try { 
                    Thread.sleep(1000); 
                } 
                catch (Exception e) 
                { 
                    System.out.println("ERRO (Sleep): " + e.getMessage()); 
                }
            }
        }
        
        tela.adicionarMensagemAoChat("[SISTEMA] Não foi possível conectar-se ao servidor.");
        System.out.println("ALERTA: Não foi possível conectar-se ao servidor " + servidorIP);
    }
    
    private void OuvirCanal(BufferedReader recebidor) {
        try {
            while (true) {
                String msg = recebidor.readLine();
                System.out.println(msg);
                tela.adicionarMensagemAoChat(msg);
            }
        } catch (Exception e) {
            System.out.println("ERRO LEITOR: " + e.getMessage());
        }
    }
    
    public void EscreverCanal(String mensagem) {
        try {
            out.println(mensagem);
            out.flush();
        } catch(Exception e) {
            System.out.println("ERRO (EscreverCanal): " + e.getMessage());
        }
    }
}