/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.ListModel;
import model.Mensagem;
import rede.SocketCliente;

/**
 *
 * @author vitor
 */
public class TelaCliente extends javax.swing.JFrame {
    TrataSocket trataSocket;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnConexao = new javax.swing.JPanel();
        btConectar = new javax.swing.JButton();
        tfConexaoEndereco = new javax.swing.JTextField();
        lbConexaoEndereco = new javax.swing.JLabel();
        tfConexaoNome = new javax.swing.JTextField();
        lbConexaoNome = new javax.swing.JLabel();
        btDesconectar = new javax.swing.JButton();
        pnOnline = new javax.swing.JPanel();
        lbOnlineTitulo = new javax.swing.JLabel();
        spOnlinePainel = new javax.swing.JScrollPane();
        lsOnlineLista = new javax.swing.JList<>();
        tfInputMensagem = new javax.swing.JTextField();
        spChat = new javax.swing.JScrollPane();
        lsChat = new javax.swing.JList<>();
        lbVersao = new javax.swing.JLabel();
        btInputEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Environmental Awareness");
        setBackground(new java.awt.Color(102, 102, 102));

        pnConexao.setBackground(new java.awt.Color(255, 255, 255));
        pnConexao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btConectar.setText("Conectar");
        btConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConectarActionPerformed(evt);
            }
        });

        lbConexaoEndereco.setText("Endereço IP:");

        lbConexaoNome.setText("Nome de usuário:");

        btDesconectar.setText("Desconectar");
        btDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesconectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnConexaoLayout = new javax.swing.GroupLayout(pnConexao);
        pnConexao.setLayout(pnConexaoLayout);
        pnConexaoLayout.setHorizontalGroup(
            pnConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnConexaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbConexaoEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfConexaoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btConectar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDesconectar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbConexaoNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfConexaoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnConexaoLayout.setVerticalGroup(
            pnConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnConexaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnConexaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConectar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfConexaoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbConexaoEndereco)
                    .addComponent(tfConexaoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbConexaoNome)
                    .addComponent(btDesconectar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnOnline.setBackground(new java.awt.Color(153, 153, 153));
        pnOnline.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lbOnlineTitulo.setBackground(new java.awt.Color(204, 204, 204));
        lbOnlineTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbOnlineTitulo.setText("ONLINE:");
        lbOnlineTitulo.setOpaque(true);

        spOnlinePainel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        lsOnlineLista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spOnlinePainel.setViewportView(lsOnlineLista);

        javax.swing.GroupLayout pnOnlineLayout = new javax.swing.GroupLayout(pnOnline);
        pnOnline.setLayout(pnOnlineLayout);
        pnOnlineLayout.setHorizontalGroup(
            pnOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOnlineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spOnlinePainel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lbOnlineTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnOnlineLayout.setVerticalGroup(
            pnOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOnlineLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbOnlineTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spOnlinePainel, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );

        tfInputMensagem.setToolTipText("");

        spChat.setAutoscrolls(true);
        spChat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lsChat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spChat.setViewportView(lsChat);

        lbVersao.setText("v0.3.1");

        btInputEnviar.setText("Enviar");
        btInputEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInputEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnConexao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spChat, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfInputMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(btInputEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(pnOnline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbVersao)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnConexao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(spChat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfInputMensagem)
                            .addComponent(btInputEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                    .addComponent(pnOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbVersao))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConectarActionPerformed
        criarConexao(tfConexaoEndereco.getText(), tfConexaoNome.getText());
    }//GEN-LAST:event_btConectarActionPerformed

    private void btInputEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInputEnviarActionPerformed
        String texto = tfInputMensagem.getText();
        
        // Não tentar enviar a mensagem se não houver conexão, ou o texto for vazio.
        if (trataSocket == null || texto == "" || texto.length() == 0) return;
        
        trataSocket.escreverCanal("Mensagem", texto);
    }//GEN-LAST:event_btInputEnviarActionPerformed

    private void btDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesconectarActionPerformed
        encerrarConexao();
        //adicionarMensagemAoChat("*** Botão temporariamente desativado ***");
    }//GEN-LAST:event_btDesconectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConectar;
    private javax.swing.JButton btDesconectar;
    private javax.swing.JButton btInputEnviar;
    private javax.swing.JLabel lbConexaoEndereco;
    private javax.swing.JLabel lbConexaoNome;
    private javax.swing.JLabel lbOnlineTitulo;
    private javax.swing.JLabel lbVersao;
    private javax.swing.JList<String> lsChat;
    private javax.swing.JList<String> lsOnlineLista;
    private javax.swing.JPanel pnConexao;
    private javax.swing.JPanel pnOnline;
    private javax.swing.JScrollPane spChat;
    private javax.swing.JScrollPane spOnlinePainel;
    private javax.swing.JTextField tfConexaoEndereco;
    private javax.swing.JTextField tfConexaoNome;
    private javax.swing.JTextField tfInputMensagem;
    // End of variables declaration//GEN-END:variables

    // Começo métodos customizados:
    // Parte visual
    public void adicionarMensagemAoChat(String mensagem) {
        // Gerar versão atualizada da lista
        ListModel lm = lsChat.getModel();
        String[] novaLista;
        
        // Recupera mensagens da lista antiga (o máximo possível)
        if (lm.getSize() >= 30) {
            novaLista = new String[lm.getSize()];        
        
            for (int i = 1; i < lm.getSize(); i++) {
                novaLista[i-1] = lm.getElementAt(i).toString();
            }
        } else {
            novaLista = new String[lm.getSize() + 1];        
        
            for (int i = 0; i < lm.getSize(); i++) {
                novaLista[i] = lm.getElementAt(i).toString();
            }
        }
        
        // Adicionar nova mensagem
        novaLista[novaLista.length - 1] = mensagem;  
        
        lsChat.setListData(novaLista);
    }
    
    public void atualizarUsuariosOnline(String nomes) {
        String[] nomesSeparados = nomes.split(",");        
        lsOnlineLista.setListData(nomesSeparados);
    }
    

    // Conexão de rede
    private void criarConexao(String servidorIP, String nomeUsuario) {
        System.out.println(nomeUsuario.length());
        
        if (nomeUsuario == "" || nomeUsuario == " " || nomeUsuario.length() < 3) {
            String alerta = "* Nome de Usuário inválido (precisa de ao menos 3 caracteres).";
            System.out.println(alerta);            
            adicionarMensagemAoChat(alerta);
            return;
        }
        
        if (trataSocket != null) {
            String alerta = "* Termine a conexão atual para começar uma nova.";
            System.out.println(alerta);            
            adicionarMensagemAoChat(alerta);
            return;
        }
        
        trataSocket = new TrataSocket(this, servidorIP, nomeUsuario);
        trataSocket.start();
    }
    
    private void encerrarConexao() {
        if (trataSocket == null) return;
        
        trataSocket.encerrarConexao();
    }
}

class TrataSocket extends Thread {
    String servidorIP;
    String nomeUsuario;
    SocketCliente socketCliente;
    TelaCliente tela;
    ObjectInputStream in;
    ObjectOutputStream out;
    
    public TrataSocket(TelaCliente tela, String ip) {
        this(tela, ip, "Usuario");
    }
    
    public TrataSocket(TelaCliente tela, String ip, String nome) {
        this.servidorIP = ip;
        this.tela = tela;
        this.nomeUsuario = nome;
    }
    
    public void run() {
        socketCliente = new SocketCliente();
        tela.trataSocket = this;
        
        boolean conectou = false;
        
        // Tentar conexão
        System.out.println("* Conectando...");
        tela.adicionarMensagemAoChat("* Conectando...");
        
        try {
            socketCliente.conectarAoServidor(servidorIP, nomeUsuario);
            conectou = true;
        } catch (Exception e) {
            System.out.println("ERRO (iniciarConexao): " + e.getMessage());
        }
        
        if (conectou) {
            in = socketCliente.retornarCanalDeEntrada();
            out = socketCliente.retornarCanalDeSaida();
            
            System.out.println("Conectou-se e instanciou os canais de dados");
            
            // Bloquear na escuta do canal
            for (int i = 0; i < 5; i++) {
                ouvirCanal();
                System.out.println("Escuta do canal de entrada perdida.");
            }
            
            System.out.println("ALERTA: Falhou em ouvir canal de entrada do socket (Provavelmente foi fechado)");
            tela.adicionarMensagemAoChat("* Conexão interrompida.");
        } else {
            tela.adicionarMensagemAoChat("* Não foi possível conectar-se ao servidor.");
            System.out.println("ALERTA: Não foi possível conectar-se ao servidor " + servidorIP);
        }
        
        // Se não há mais conexão:
        tela.atualizarUsuariosOnline("");
        tela.trataSocket = null;
    }
    
    private void ouvirCanal() {
        try {
            while (true) {
                interpretarMensagem((Mensagem)in.readObject());
            }
        } catch (Exception e) {
            System.out.println("ERRO (ouvirCanal): " + e.getMessage());
        }
    }
    
    private void interpretarMensagem(Mensagem msg) {
        System.out.println("Interpretando mensagem");
        
        switch (msg.getTipo()) {
            case "Mensagem":
                System.out.println("Mensagem padrão identificada");
                String mensagem = msg.retornarMensagemFormatada();
                System.out.println(mensagem);
                tela.adicionarMensagemAoChat(mensagem);
                break;
            case "AtualizarOnline":
                System.out.println("Notificação de conexão identificada");
                tela.atualizarUsuariosOnline(msg.getConteudo());
                break;
            case "Arquivo":
                System.out.println("Alerta de envio de arquivo identificado");
                break;
            default:
                System.out.println("ERRO: Tipo de mensagem não identificada.");
                break;
        }
    }
    
    public void escreverCanal(String tipo, String conteudo) {
        if (tipo == "Mensagem") conteudo = nomeUsuario + ": " + conteudo;
        
        try {
            out.writeObject(new Mensagem(tipo, conteudo));
            out.flush();
        } catch(Exception e) {
            System.out.println("ERRO (EscreverCanal): " + e.getMessage());
        }
    }
    
    public void encerrarConexao() {
        try {
            socketCliente.encerrarConexao();
        } catch(Exception e) {
            System.out.println("ERRO (encerrarConexao): " + e.getMessage());
        }
    }
}